spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOST:mongo}:${MONGO_PORT:27017}/${MONGO_DB}?authSource=admin
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  elasticsearch:
    repositories:
      enabled: ${MIXCHAT_SEARCH_ENABLED:true}
    auto-index-creation: ${MIXCHAT_SEARCH_ENABLED:true}

server:
  port: 8080

logging:
  level:
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
    com.back: INFO
custom:
  site:
    cookieDomain: "${custom.prod.cookieDomain}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"
    name: mixchat
# 운영 단계에선 actuator 전용 포트 사용
management:
  server:
    port: 9100

mixchat:
  search:
    enabled: ${MIXCHAT_SEARCH_ENABLED:true}
